### ISSUE TITLE
Issue with IPN, anonymous transaction each time and group not automaticly change 

### ISSUE THREAD

**Issue by RetroGameSets** [Skouat/ext_paypal_donation#98] opened 2022-05-29 14:11 UTC
Hi 

since 2 or 3 days I have an issue . EVERY donations on my forum are made as 'anonymous' / guest , not with the forum usernames so not showing on notifications and history control panel.

anonymous donate is disable since the beginning on my forum so you need to have an account to make a donation.

now, some members are not automaticly passed to the donate group after their donation because extension does not recognize the username

All has been working from few years.. 

here is one log I have modified name/id  

can you help please ?

my forum is on phpbb 3.5  . alors extension shows that tls1.2 is not supported but I verified here https://www.ssllabs.com/ssltest/analyze.html?d=psa-diag.fr and support tls 1.2/ 1.3 . I had to modify the line on ipn_paypal.php from `$this->config->set('ppde_tls_detected', false); ` to `$this->config->set('ppde_tls_detected', true); `  to be able to activation IPN.

[ppde_tx_1653827446_bqdzt2akuuae23l1.log](https://github.com/Skouat/ext_paypal_donation/files/8793490/ppde_tx_1653827446_bqdzt2akuuae23l1.log)

**Comment by RetroGameSets** [comment] 2022-05-29 17:58
I have one donation who has passed don't know why .. no difference

I see that 'object number' line is good filled by uid_xxx where xxx corresponding to member ID so all is okay.. on other transactions this line is empty .. on paypal mail or transaction history of extension.

**Comment by Skouat** [comment] 2022-05-29 18:48
Hi,

> my forum is on phpbb 3.5

Please can you confirm your phpBB version?
Which version of PPDE is installed?

>  extension shows that tls1.2 is not supported

The TLS test consist to access the following web page : https://www.howsmyssl.com/a/check then get the response and verify that the response contains `TLS 1.2` or `TLS 1.3`
Are you able the run `curl https://www.howsmyssl.com/a/check` via CLI on your webserver ?
You will see the response.

> I see that 'object number' line is good filled by uid_xxx where xxx corresponding to member ID so all is okay.. on other transactions this line is empty .. on paypal mail or transaction history of extension.

Indeed, if the `item_number` is empty, it will result an anonymous donation.
Does your board allow anonymous donation?

Can you check your [PayPal History](https://www.paypal.com/cgi-bin/webscr?cmd=_display-ipns-history) and confirm that the Item_number is also empty?

**Comment by skymike03** [comment] 2022-05-29 19:11
Hi,

Which PHPBB  and version of PPDE is installed?

PHPBB 3.3.5 sorry  with last ppde 3.0.4 i just updated today because it was a random problem 2 days ago so I thinked it was just an update to do , but not helping. 

Are you able the run curl https://www.howsmyssl.com/a/check via CLI on your webserver ?
You will see the response.

curl https://www.howsmyssl.com/a/check on my web interface gives : 
curl: (51) Unable to communicate securely with peer: requested domain name does not match the server's certificate.


Indeed, if the item_number is empty, it will result an anonymous donation.
Does your board allow anonymous donation?Can you check your PayPal History and confirm that the Item_number is also empty?

My board doesn't allow anonymous transactions and I never activated it. only registred members can donate and they were moved automaticly into new group after..
In paypal history  , item number is empty too.Message ID: ***@***.***>


thank you

Mike.

**Comment by RetroGameSets** [comment] 2022-05-29 19:12
Hi,

Which PHPBB  and version of PPDE is installed?

`PHPBB 3.3.5 sorry  with last ppde 3.0.4 i just updated today because it was a random problem 2 days ago so I thinked it was just an update to do , but not helping. `

Are you able the run curl https://www.howsmyssl.com/a/check via CLI on your webserver ?
You will see the response.

`
curl https://www.howsmyssl.com/a/check on my web interface gives : 
curl: (51) Unable to communicate securely with peer: requested domain name does not match the server's certificate.
dev tools in chrome says connection is crypted and use TLS1.3`


Indeed, if the item_number is empty, it will result an anonymous donation.
Does your board allow anonymous donation?Can you check your PayPal History and confirm that the Item_number is also empty?

`
My board doesn't allow anonymous transactions and I never activated it. only registred members can donate and they were moved automaticly into new group after..
In paypal history  , item number is empty too..
`


thank you

Mike.

**Comment by RetroGameSets** [comment] 2022-05-30 15:07
Hi

A new information.

If the donor email on PayPal is same of email on the forum, the member seems to be changed automatically on the group for donors.

But if not, nothing happens.

In all cases, transaction is still show on anonymous and I don't have notification on the forum of the donation.

**Comment by Skouat** [comment] 2022-05-30 17:48
HI,

Yes, if the email address exists it links the donation to the user.

What I don't understand, it's why your board doesn't provide the item_number to PayPal.
Please, can you provide a test account with basic user rights and, at least, access rights to the donation page.
Thanks.

**Comment by RetroGameSets** [comment] 2022-05-30 17:51
Hi, you can create an account its free
https://www.psa-diag.fr/forum/ucp.php?mode=register 

You will have all rights to acces forum as registred member. The only difference for donors is a hidden category 

. Or you want acces to ACP with access to PPDE control settings ? if so, is there a way to contact you by pm (facebook / whatsapp / mail ..?)

**Comment by RetroGameSets** [comment] 2022-06-01 14:35
please help :(

**Comment by Skouat** [comment] 2022-06-01 20:25
Hi,

When the donate page redirects to PayPal, we can see that the item_number is properly sent to PayPal.
So, it doesn't make sense that this value is dropped by PayPal if the data is well forwarded.

Did you test PayPal Sandbox?
If you don't have PayPal Sandbox account, you can read [this page](https://github.com/Skouat/ext_paypal_donation/wiki/Testing-accounts-information#paypal-sandbox-testing-accounts-information)

**Comment by RetroGameSets** [comment] 2022-06-02 19:09
sandbox seams not working

i've done setting I have "merchant testing store" , enter the testing credentials and when i click send stuck on the screen please wait

![image_2022-06-02_210910967](https://user-images.githubusercontent.com/102905084/171718458-fc291fc4-53d8-48eb-89e0-b7f56ce536e0.png)

**Comment by RetroGameSets** [comment] 2022-06-02 19:12
but yes, with a test account UID is shown before payment..
![image_2022-06-02_211206594](https://user-images.githubusercontent.com/102905084/171719368-e80d82ba-7bbd-40a7-98f1-c8d36772b709.png)

**Comment by RetroGameSets** [comment] 2022-06-02 19:21
I see I'm not only to have this problem
https://www.phpbb.com/customise/db/extension/paypal_donation_extension/support/topic/237471
or
https://www.phpbb.com/customise/db/extension/paypal_donation_extension/support/topic/236716?p=836516#p836516

**Comment by Skouat** [comment] 2022-06-02 21:50
> I see I'm not only to have this problem

One of them is not the same issue.

**Comment by Unaacaso** [comment] 2022-06-03 07:45
Hi, I also have this exact problem.

I tried to activate the sandbox as indicated [here](https://github.com/Skouat/ext_paypal_donation/wiki/Testing-accounts-information#paypal-sandbox-testing-accounts-information) but it only made the situation worse.

Now whatever configuration I set in the "PayPal IPN Features" screen I get this.

![paypal_DE](https://user-images.githubusercontent.com/106802933/171810495-e93d32c5-6bc3-4f18-9d82-6b2a7e15a579.jpg)

This is my last log

[ppde_tx_1654240780_d0c92874f488e413.log](https://github.com/Skouat/ext_paypal_donation/files/8830492/ppde_tx_1654240780_d0c92874f488e413.log)

I want to point out that the version of my Phpbb is 3.2.3 and the version of the extension is 2.0.1

Until a few weeks ago everything was working regularly.

Can you help me please?

Thank you.

**Comment by Unaacaso** [comment] 2022-06-03 09:23
I add that, in the overview, I see **TLS 1.2 and HTTP / 1.1: Not detected** but the system engineers of my server, with whom I opened a ticket, tell me that «_all the elements of our server (Apache, PHP, cUrl, etc. ) support both TLS 1.2 and HTTP 1.1_».
![TLS](https://user-images.githubusercontent.com/106802933/171827363-ab82ef03-b8d4-49a0-a429-5b680d1802d1.jpg)

**Comment by RetroGameSets** [comment] 2022-06-03 09:25
Tls has never been detected for me. I had to manually edit a file to bypass it but it worked for few years since now..

**Comment by RetroGameSets** [comment] 2022-06-03 09:28
> I add that, in the overview, I see **TLS 1.2 and HTTP / 1.1: Not detected** but the system engineers of my server, with whom I opened a ticket, tell me that «_all the elements of our server (Apache, PHP, cUrl, etc. ) support both TLS 1.2 and HTTP 1.1_». ![TLS](https://user-images.githubusercontent.com/106802933/171827363-ab82ef03-b8d4-49a0-a429-5b680d1802d1.jpg)

 I had to modify the line on ipn_paypal.php from $this->config->set('ppde_tls_detected', false); to $this->config->set('ppde_tls_detected', true); to be able to activation IPN.

**Comment by Unaacaso** [comment] 2022-06-03 11:04
@skymike03 I made the change you suggested and now IPN works, even if in the overview I always read TLS not dectect. Unfortunately, the transaction log is still not working.

I hope for an improvement.

**Comment by Skouat** [comment] 2022-06-03 17:54
Hi @skymike03 @Unaacaso 
First of all, please update the extension to [2.1.5](https://www.phpbb.com/customise/db/extension/paypal_donation_extension/).
This will fix your issue with TLS 1.2 and, maybe some other stuff related to PayPal.

**Comment by RetroGameSets** [comment] 2022-06-03 18:06
@Skouat
Hi you mean downgrade? Because I'm on last version 3.0.4

**Comment by Skouat** [comment] 2022-06-03 18:33
Sorry... it's only for @Unaacaso 
I forgot that you are using 3.0.4

For your issue it's an another story.
I fear the worst about PPDE :/
PayPal seems has made changes. But I don't know what they are.
I have to investigate... and maybe globally refactor the extension 😭

**Comment by RetroGameSets** [comment] 2022-06-03 18:39
> Sorry... it's only for @Unaacaso I forgot that you are using 3.0.4
> 
> For your issue it's an another story. I fear the worst about PPDE :/ PayPal seems has made changes. But I don't know what they are. I have to investigate... and maybe globally refactor the extension 😭

I tried to deactivate then update to 2.1.5 (downgrade) and reactivate..
I connected with test account and made a donation... All was working... Auto group, notification, and transaction log doesn't show anonymous..
Control panel shows now "tls and http1 verification is disable.

So all seems to work with this version... I'm waiting for real user tests

**Comment by Skouat** [comment] 2022-06-03 19:56
@skymike03 I never said that you have to downgrade. :/
The version 2.1.5 is not compatible with phpBB 3.3
Please reinstall the release 3.0.4

**Comment by RetroGameSets** [comment] 2022-06-03 19:58
@Skouat
Yes I know you didn't said that.. But since I downgrade all is working...
I don't know why...

**Comment by Skouat** [comment] 2022-06-03 23:13
@skymike03 please can you go back to [PayPal IPN History](https://www.paypal.com/ie/cgi-bin/webscr?cmd=_display-ipns-history&nav=0.3.2) and send me, via PM on phpBB.com or phpBB-fr.com, the following data ?

- A screenshot of the Message ID details
  Click on the message ID number
![image](https://user-images.githubusercontent.com/416780/171964236-b224d21b-f551-4ebd-b8dd-a86a3c99f788.png)
  Then take a screenshot of the page. You can blur the "IPN message" part of the image.
- A copy of the "IPN Message"
  you can make personal data anonymous (Name, address, email)
  Do not remove data or empty the fields

Please select the transaction ID related to the log you shared in your first message and the most recent successful transaction.

Thanks

**Comment by RetroGameSets** [comment] 2022-06-04 09:28
hi @Skouat  

I'm sorry but I cant to this because it's personnal account so paypal doesn't let me acces IPN History...

**Comment by Skouat** [comment] 2022-06-04 09:52
Hmmm...
As you have seen, the IPN requires a business account. I am surprised that IPN works with a personal account.
I suggest you upgrade to a business account.
It's free of charge and does'nt change anything on PayPal, except that it gives you access to more features, like IPN :)
=> https://www.phpbb.com/customise/db/extension/paypal_donation_extension/faq/2051

Are you still using PPDE 2.1.5 or have you go back to version 3.0.4?

**Comment by RetroGameSets** [comment] 2022-06-04 10:05
Yes I have access to IPN notification settings page. But not history only 😁
Didn't have problems since few years...

Still using 2.0.5 for now but I didn't receive donations since my only test yesterday which worked..

**Comment by Skouat** [comment] 2022-06-04 11:16
> Yes I have access to IPN notification settings page. But not history only 😁 Didn't have problems since few years...


Good to know.


> Still using 2.0.5 for now but I didn't receive donations since my only test yesterday which worked.

Are you sure it really worked?
Can you check the PPDE transaction log to ensure that the field "payer email address" is not the same as the one set in your phpBB account?
If it is the case, that why it worked.

**Comment by RetroGameSets** [comment] 2022-06-04 11:56
Yes it worked because I've done the donation myself and didn't use same email. I received notification on forum too. Auto group worked and transaction was not anonymous.. 
But now it's not working I received 2 donations and  same problem than before.. Anonymous and no notification.. It works just one time

**Comment by Skouat** [comment] 2022-06-04 12:12
I don't know how to fix this, because it's an issue on PayPal side.  
I am afraid that PayPal will no longer provide support for this feature.   
I will try to contact them.

Until now, I recommend that you reinstall PPDE 3.0.4 (with the workaround you applied for the TLS detection)
This release provides more features and fix.

**Comment by RetroGameSets** [comment] 2022-06-04 12:40
yes I just reinstalled 3.0.4 with the workaround now...  the thing I didn't understand is that it worked 1 time yesterday after i downgrade.. I had some hope but finally not... I will continue to ask users to modify their email adress on board before donation for workaround... i will not received notifications and always be anonymous transactions but they will have access to donate section it's the most important for now...

**Comment by RetroGameSets** [comment] 2022-06-04 12:58
question please. what should the url be here on IPN notifcation settings of paypal ?? 

https://psa-diag.fr/forum/donate?return=success

or 

https://psa-diag.fr/forum/ipn-listener
???


![image_2022-06-04_145650005](https://user-images.githubusercontent.com/102905084/172000034-0005d278-c10a-4722-b953-cada464265de.png)

**Comment by Skouat** [comment] 2022-06-04 13:54
It doesn't matter because PPDE override the value entered here.
This URL is used only if you receive donation from a source that doesn't provide the "notify_url" argument.

So you can define : https://psa-diag.fr/forum/ipn-listener

**Comment by Skouat** [comment] 2022-06-04 14:03
FYI, I tested on my own and also encountered the issue.
So, it's not necessary to provide the information I requested earlier.

**Comment by RetroGameSets** [comment] 2022-06-04 14:12
> FYI, I tested on my own and also encountered the issue. So, it's not necessary to provide the information I requested earlier.

oh, so you have same issue than me on your own board ? so it's paypal issue...

**Comment by Unaacaso** [comment] 2022-06-06 08:34
Hi @Skouat , as you can see from the image, I was able to successfully update PPDE to the latest version available for my phpBB 3.2.3.

Unfortunately, the problem of anonymous donations (even with a logged in user) continues to exist.

What do you advise me to do?

Thank you
![PPDE](https://user-images.githubusercontent.com/106802933/172125809-0f9207d2-26c0-4569-affd-9d67d989a39b.jpg)
.

**Comment by Skouat** [comment] 2022-06-10 20:03
Hi @Unaacaso
If you read my previous comments, you can understand that the issue is with Paypal.
Currently, I have no idea how to solve this and if it could require a global refactor of PPDE, I will have to find the time to do this.
But unfortunately, time is not something we can earn when we don't have it.

As you updated PPDE to 2.1.5 (or upper those that are under phpBB 3.3.x) you can reassign donation to the right member by using the feature available in the "Transactions Log"

**Comment by v12mike** [comment] 2022-06-12 07:27
Have you tried embedding the uid in a different Paypal filed, like "custom"?

**Comment by Skouat** [comment] 2022-06-12 11:12
Hi,

Thanks to @v12mike for the tips.

@skymike03 @Unaacaso
Please can you update the files listed in the patch that correspond to your version of PPDE?

- [PPDE 3.0.4 -](https://github.com/Skouat/ext_paypal_donation/commit/72ad3e7cd38ea7cb67bf3d7e65a27e2b96d338b6) [Fix](https://github.com/Skouat/ext_paypal_donation/commit/72ad3e7cd38ea7cb67bf3d7e65a27e2b96d338b6) https://github.com/Skouat/ext_paypal_donation/issues/98
- [PPDE 2.1.5 -](https://github.com/Skouat/ext_paypal_donation/commit/15b2f7f9d2b9093b9acaf8cd5f404e418e86306c) [Fix](https://github.com/Skouat/ext_paypal_donation/commit/15b2f7f9d2b9093b9acaf8cd5f404e418e86306c) https://github.com/Skouat/ext_paypal_donation/issues/98

**Comment by RetroGameSets** [comment] 2022-06-12 11:24
Hi @Skouat 
okay i just done the update fix to my board... waiting

![image_2022-06-12_132340114](https://user-images.githubusercontent.com/102905084/173230784-943a41f9-3661-406c-b9c9-ab192743f879.png)

**Comment by v12mike** [comment] 2022-06-12 17:04
It works for me :-))

**Comment by RetroGameSets** [comment] 2022-06-12 17:31
Hi it seems to work for me too. 
Auto group ok even if email is not same on PayPal 
Transaction not anonymous 
But no notification on the board of the donation

**Comment by Skouat** [comment] 2022-06-12 17:36
> But no notification on the board of the donation

It works, this is not an issue with the extension. Check PPDE IPN settings and your UCP settings.

**Closed as completed** 2022-06-12 17:39 UTC

**Comment by Unaacaso** [comment] 2022-06-13 17:00
Hi @Skouat, I have completely replaced the files

- actions/core.php
- controller/admin/transactions_controller.php
- controller/ipn_listener.php
- controller/main_donate.php
- operators/transactions.php

for version 2.1.5 and I have the following problems:

- no notification of donation
- "Transactions log" page does not work
- Overview page does not work

I attach here the modified files, maybe I did something wrong?
[modified.zip](https://github.com/Skouat/ext_paypal_donation/files/8893063/modified.zip)

**Comment by Skouat** [comment] 2022-06-13 17:49
Hi,

> * "Transactions log" page does not work
> * Overview page does not work

Should I buy a crystal ball to know what doesn't work?
Please provide more details.

Also, this ticket being closed and your problem being different. Please open another ticket (here or on phpBB.com)
