### ISSUE TITLE
Call to undefined method phpbb\event\data::update_subarray() in ext/skouat/ppde/event/listener.php on line 159

### ISSUE THREAD

**Issue by jonnyrrr** [Skouat/ext_paypal_donation#56] opened 2017-09-05 13:31 UTC
Please forgive me if I am not doing this correctly as I am a complete newbie to this.

I successfully installed this extension for testing on phpBB 3.2.0 on 4 Sept 2017, it installs and works fine, however once it is installed the permissions tab in ACP no longer works and gives a HTTP ERROR 500, as soon as this extension is disabled the ACP permissions tab works. Have I missed something obvious or made a mistake in my installation or is it a genuine bug?

Regards
     Complete Newbie

**Comment by Skouat** [comment] 2017-09-05 20:30
Hi,

It make no sense that you encounter this error when you just go in ACP tab.

Please, enable the extension, go in your ACP tab to reproduce the error 500.
Then check your WebServer log for retrieve this error on logs.

**Comment by jonnyrrr** [comment] 2017-09-09 14:18
Thank you for the advice, I am in the process of doing just that but I have
a big problem with my web host (who I will not name at present) as they are
not correctly logging errors via cpanel, when this is corrected I should be
able to see the cause I hope, another thing I have noticed but this maybe
because this extension is not yet released is that the donation header link
is only visible and accessible by phpbb admins, or is this another clue to
my current problem, I have done a complete removal and re-install twice and
I have noticed that the first few times I am able to access the Permissions
Tab in the ACP, but then after a few accesses is just returns the 500 error
until the ppde extension is disabled, you are right it makes no sense, but
it is happening, everything else on my phpBB 3.2.0 including all over
extensions are working perfectly. I will keep you posted on any
developments.

Regards
         Jonathan...

**Comment by Skouat** [comment] 2017-09-09 15:51
Hi,

Mabye you have a global issue with your permissions and your phpbb_acl_* tables are corrupted.
Check you board integrity with STK for phpBB 3.2 (use it at your own risk).

> another thing I have noticed but this maybe
because this extension is not yet released is that the donation header link
is only visible and accessible by phpbb admins, or is this another clue to
my current problem  

The header link is a feature based on phpBB permissions.
By default, only the role "All Features" sets this feature to "YES".
If this role is assigned to a group, then all its members can see the header link.

**Comment by jonnyrrr** [comment] 2017-09-10 23:07
Hi

I have found the error or at least an error log entry that gets written
when clicking on the permissions tab in phpBB ACP :-

PHP Fatal error:  Call to undefined method
phpbb\event\data::update_subarray() in
/home/isscomne/public_html/phpbb/ext/skouat/ppde/event/listener.php on line
159


Regards
     Jonathan...

**Comment by Skouat** [comment] 2017-09-11 21:06
Thanks for the error message. It's very useful.

My bad... I use a method only available in phpBB 3.2.1.
Please can you update your board to 3.2.1? (it's recommended 😄)
In the meantime I will decide if I apply a regression fix or change the Extension prerequisites to be only available with phpBB 3.2.1

**Comment by jonnyrrr** [comment] 2017-09-11 23:13
Glad it helped, I have upgraded to 3.2.1 so the ACP permissions tab now
works fine, thanks for your help.

**Closed as completed** 2017-11-12 16:00 UTC
Labels: bug, Blocker
